# docker-composeのファイル形式のバージョン/3が最新
version: '3'
# 一つのサービスで一つのコンテナが起動する
services: 
  db: 
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code
    ports:
      - "8000:8000"
    # webサービスが立ち上がる前に、dbサービスが立ち上がるようにしている
    depends_on:
      - db